### ISSUE TITLE
Add Adanos market sentiment data plugin

### ISSUE THREAD

**Issue by alexander-schneider** [kestra-io/kestra#17605]
### Feature description

Add an official `plugin-adanos` for read-only market sentiment and attention workflows.

Adanos provides structured stock sentiment across Reddit, X / FinTwit, financial news, and Polymarket, plus Reddit crypto sentiment. A dedicated plugin would let Kestra users schedule sentiment snapshots, identify trending assets, compare assets, and feed market-level context into reporting, alerting, and data pipelines without maintaining custom HTTP tasks.

Proposed v1:

1. Repository and category
   - Create `kestra-io/plugin-adanos` from `plugin-template`.
   - Use package namespace `io.kestra.plugin.adanos`.
   - Use the `DATA` plugin category.
   - Include the required plugin/subgroup icons, metadata, documentation, and complete flow examples.

2. Shared connection behavior
   - `apiKey` as a secret property, sent only through the documented `X-API-Key` header.
   - Optional `baseUrl`, defaulting to `https://api.adanos.org`.
   - Kestra HTTP client configuration and `FetchType` support so responses can be returned inline or stored in internal storage.
   - Common date-window properties: `from`, `to`, or `days`.

3. Initial read-only tasks
   - Stock asset sentiment for a ticker, with source selection across Reddit, X / FinTwit, News, and Polymarket.
   - Stock trending assets, asset comparison, and market sentiment with the same source selection.
   - Crypto token sentiment, trending assets, asset comparison, and market sentiment for the currently supported Reddit crypto dataset.

   The plugin would map those tasks to the existing versioned REST endpoints rather than adding a generic arbitrary-request task. Free API keys can exercise this core scope. Professional-only raw mention and AI explanation endpoints would stay out of v1.

4. Kestra-native outputs and validation
   - Structured response body for `FETCH`.
   - Internal-storage URI for `STORE`.
   - Result count and pagination fields where the endpoint provides them.
   - Validate source/asset combinations before issuing a request.
   - Preserve Adanos non-2xx status and error detail without logging credentials.

5. QA
   - Unit tests against a fake HTTP controller; no live API key required.
   - Cover authentication headers, endpoint routing, date/query rendering, ticker/symbol encoding, comparison parameters, pagination, `FetchType.STORE`, invalid combinations, and non-2xx responses.
   - Add flow fixtures and run the standard Gradle tests, formatting checks, and `lintPluginDocs`.
   - Include a reproducible flow in the implementation PR.

Example use cases:
- Store daily Reddit and X sentiment for a stock watchlist.
- Alert when an asset enters a platform's trending results.
- Compare sentiment and buzz across candidate assets before a downstream research step.
- Add broad market sentiment to a scheduled report or warehouse pipeline.

References:
- API documentation: https://api.adanos.org/docs
- OpenAPI definition: https://api.adanos.org/openapi.json
- API key registration: https://adanos.org/register
- Kestra plugin developer guide: https://kestra.io/docs/plugin-developer-guide

I reviewed `plugin-template`, the contribution guidelines, and the recent `plugin-xquik` creation flow. If this scope and category look appropriate, I can prepare the implementation PR against the repository location the maintainers prefer.

**Comment by fdelbrayelle** [comment]
Hello @alexander-schneider :wave:
Thank you for your proposal. I scaffolded the plugin repo here: https://github.com/kestra-io/plugin-adanos
Could you open a PR that follows our [plugin guidelines](https://kestra.io/docs/plugin-developer-guide/contribution-guidelines)?
Thanks! 🙏

**Comment by alexander-schneider** [comment]
Thanks for scaffolding the repository. I opened kestra-io/plugin-adanos#2 with the initial Adanos integration.

It follows the plugin guidelines and includes four typed read-only tasks, Kestra-native HTTP and `FetchType` handling, secret-safe authentication, stock/crypto validation, plugin metadata and icons, documentation, a reproducible flow, and fake-controller tests. The implementation follows the current OpenAPI contract and uses `from`/`to` without the deprecated `days` parameter.

Local verification is green: 13 tests, all 25 plugin documentation lint rules, Shadow JAR packaging, and registration of all four tasks in a local Kestra instance.

**Comment by Pradumnasaraf** [comment]
QA Done ✅. All tasks are working on 1.3.x. CC @aj-emerich for sample code in case you need it!


### io.kestra.plugin.adanos.GetAssetSentiment ✅

```yaml
id: adanos_asset_sentiment
namespace: company.research
description: GetAssetSentiment for a stock (Reddit) and a crypto token (Reddit).

tasks:
  - id: stock_reddit_sentiment
    type: io.kestra.plugin.adanos.GetAssetSentiment
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: STOCK
    source: REDDIT
    symbol: TSLA
    fetchType: FETCH

  - id: crypto_reddit_sentiment
    type: io.kestra.plugin.adanos.GetAssetSentiment
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: CRYPTO
    source: REDDIT
    symbol: BTC
    fetchType: FETCH

  - id: log_results
    type: io.kestra.plugin.core.log.Log
    message: |
      stock size={{ outputs.stock_reddit_sentiment.size }} buzz={{ outputs.stock_reddit_sentiment.body.buzz_score }} sentiment={{ outputs.stock_reddit_sentiment.body.sentiment_score }}
      crypto size={{ outputs.crypto_reddit_sentiment.size }} body={{ outputs.crypto_reddit_sentiment.body }}
```

### io.kestra.plugin.adanos.ListTrendingAssets ✅

```yaml
id: adanos_trending
namespace: company.research
description: ListTrendingAssets for stocks (X / FinTwit) and crypto (Reddit) with pagination.

tasks:
  - id: trending_x_stocks
    type: io.kestra.plugin.adanos.ListTrendingAssets
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: STOCK
    source: X
    limit: 5
    offset: 0
    stockAssetType: ALL
    fetchType: FETCH

  - id: trending_crypto_reddit
    type: io.kestra.plugin.adanos.ListTrendingAssets
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: CRYPTO
    source: REDDIT
    limit: 5
    offset: 0
    fetchType: FETCH

  - id: log_results
    type: io.kestra.plugin.core.log.Log
    message: |
      x_stocks size={{ outputs.trending_x_stocks.size }}
      crypto size={{ outputs.trending_crypto_reddit.size }}
```

### io.kestra.plugin.adanos.CompareAssets ✅

```yaml
id: adanos_compare
namespace: company.research
description: CompareAssets for stocks (News, tickers param) and crypto (Reddit, symbols param).

tasks:
  - id: compare_news_stocks
    type: io.kestra.plugin.adanos.CompareAssets
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: STOCK
    source: NEWS
    symbols:
      - TSLA
      - NVDA
      - AMD
    fetchType: FETCH

  - id: compare_crypto_reddit
    type: io.kestra.plugin.adanos.CompareAssets
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: CRYPTO
    source: REDDIT
    symbols:
      - BTC
      - ETH
      - SOL
    fetchType: FETCH

  - id: log_results
    type: io.kestra.plugin.core.log.Log
    message: |
      news_stocks size={{ outputs.compare_news_stocks.size }}
      crypto size={{ outputs.compare_crypto_reddit.size }}
```

### io.kestra.plugin.adanos.GetMarketSentiment ✅

```yaml
id: adanos_market_sentiment
namespace: company.research
description: GetMarketSentiment for stocks via Polymarket and Reddit sources.

tasks:
  - id: market_polymarket
    type: io.kestra.plugin.adanos.GetMarketSentiment
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: STOCK
    source: POLYMARKET
    fetchType: FETCH

  - id: market_reddit_stocks
    type: io.kestra.plugin.adanos.GetMarketSentiment
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: STOCK
    source: REDDIT
    fetchType: FETCH

  - id: log_results
    type: io.kestra.plugin.core.log.Log
    message: |
      polymarket size={{ outputs.market_polymarket.size }} body={{ outputs.market_polymarket.body }}
      reddit size={{ outputs.market_reddit_stocks.size }} body={{ outputs.market_reddit_stocks.body }}
```

### FetchType STORE ✅

```yaml
id: adanos_store_mode
namespace: company.research
description: FetchType STORE writes the Adanos response to Kestra internal storage and returns a URI.

tasks:
  - id: store_sentiment
    type: io.kestra.plugin.adanos.GetAssetSentiment
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: STOCK
    source: NEWS
    symbol: NVDA
    fetchType: STORE

  - id: log_uri
    type: io.kestra.plugin.core.log.Log
    message: "stored size={{ outputs.store_sentiment.size }} uri={{ outputs.store_sentiment.uri }}"
```

### Guardrail: crypto + non-Reddit source ✅

```yaml
id: adanos_invalid_combo
namespace: company.research
description: Guardrail check - crypto with a non-Reddit source must be rejected before any HTTP call.

tasks:
  - id: crypto_with_news_source
    type: io.kestra.plugin.adanos.GetMarketSentiment
    apiKey: "{{ secret('ADANOS_API_KEY') }}"
    assetType: CRYPTO
    source: NEWS
    fetchType: FETCH
```


<img width="1274" height="1080" alt="Screenshot 2026-07-24 at 12 43 25 PM" src="https://github.com/user-attachments/assets/08dae535-ead6-4a39-adb5-c6b9122c49ef" />

---

FOR NOTE (you might already know @fdelbrayelle): The plugin is not working and is not compatible with 2.0.0

**Comment by fdelbrayelle** [comment]
Hi @alexander-schneider 👋 
The plugin is now available in v1.0.0: https://kestra.io/plugins/plugin-adanos
Thanks for your contribution!

**Comment by fdelbrayelle** [comment]
Hi @Pradumnasaraf :wave:
Could you provide more details about why it's not working with Kestra 2.0.0 ?
Couldn't it be related to the recent issue on our 2.0.0 test environment this morning?

**Comment by Pradumnasaraf** [comment]
Hey @fdelbrayelle, I was getting this error with all the tasks when I tried to run with 2.0.0: `java.lang.NoSuchMethodError: HttpConfiguration$HttpConfigurationBuilder.maxContentLength(java.lang.Integer)`

**Comment by fdelbrayelle** [comment]
@Pradumnasaraf I opened [a PR](https://github.com/kestra-io/plugin-adanos/pull/3) to remove the deprecated field so that I'll work also on Kestra 2.0.0.

**Comment by Pradumnasaraf** [comment]
Re-QA done ✅. Working with. 2.0.0 with v1.0.1 of the plugin. Used the same flows above


<img width="1278" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d27cde11-6ec4-43f9-8677-3bea15f9bd53" />
